In [1]:
import numpy as np

In [5]:
A = np.array([1, 2, 3, 4])
print(A)
np.ndim(A)
A.shape
A.shape[0]

[1 2 3 4]


4

In [8]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)
np.ndim(B)
B.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [11]:
A = np.array([[1,2], [3,4]])
A.shape
B = np.array([[5,6], [7,8]])
B.shape
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [12]:
A = np.array([[1,2,3], [4,5,6]])
A.shape
B = np.array([[1,2], [3,4], [5,6]])
B.shape
np.dot(A, B)

array([[22, 28],
       [49, 64]])